source 'https://rubygems.org'

gem 'pg'
gem 'puma', '2.6.0'

# Run-time dependencies
gem 'rails', '3.2.19'
gem 'rails_autolink', '1.1.3'
gem 'nokogiri', '1.5.11'
gem 'rdoc', '3.12.2', :require => false
gem 'geokit', '1.6.5'
gem 'htmlentities', '4.3.1'
gem 'paper_trail', '2.7.2'
gem 'ri_cal', '0.8.8'
gem 'rubyzip'
gem 'will_paginate', '3.0.5', require: ['will_paginate', 'will_paginate/array']
gem 'httparty', '0.11.0'
gem 'loofah', '1.2.1'
gem 'loofah-activerecord', '1.1.0'
gem 'bluecloth', '2.2.0'
gem 'formtastic', '2.2.1'
gem 'acts-as-taggable-on', '2.4.1'
gem 'jquery-rails', '1.0.19'
gem 'progress_bar', '1.0.0'
gem 'exception_notification', '2.6.1'
gem 'font-awesome-rails', '3.2.1.3'
gem 'paper_trail_manager', '>= 0.2.0'
gem 'utf8-cleaner', '~> 0.0.6'
gem 'rack-robustness', '~> 1.1.0'
gem 'sunspot_rails', '2.1.1'
gem 'sunspot_solr',  '2.1.1'
gem 'lucene_query', '0.1'
